<a href="https://colab.research.google.com/github/farhadrahimiinfo/Machine_Learning/blob/main/Iris_Species_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

import numpy as np

!pip install mglearn

import sys
!{sys.executable} -m pip install mglearn

import mglearn

from sklearn.datasets import load_iris
iris_dataset=load_iris()

from sklearn.datasets import load_iris
iris_dataset=load_iris()

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 41.0 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
print("keys:",iris_dataset.keys())


keys: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
print(iris_dataset['DESCR'][:193])


.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre


In [5]:
print("Target names:",iris_dataset["target_names"])


Target names: ['setosa' 'versicolor' 'virginica']


In [6]:
print("Features name=",iris_dataset["feature_names"])


Features name= ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print("Type of data:",type(iris_dataset["data"]))


Type of data: <class 'numpy.ndarray'>


In [8]:
print("Shape of data=",iris_dataset["data"].shape)


Shape of data= (150, 4)


In [9]:
print("First five rows of data:\n",iris_dataset['data'][:5])


First five rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [10]:
print("Type of target:",type(iris_dataset['target']))


Type of target: <class 'numpy.ndarray'>


In [11]:
print("Type of target:",type(iris_dataset['target'].shape))


Type of target: <class 'tuple'>


In [12]:
print("Type of target:",iris_dataset['target'].shape)


Type of target: (150,)


In [13]:
print("Type of target:",iris_dataset['target'])


Type of target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [14]:
#Measururing Success: Training and Testing Data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

print("x_train shape=",x_train.shape)
print("y_train=",y_train.shape)

print("x_test shape=",x_test.shape)
print("y_test=",y_test.shape)


x_train shape= (112, 4)
y_train= (112,)
x_test shape= (38, 4)
y_test= (38,)


In [15]:
#create dataframe from data in x_train
#lable the columns using the strings in Iris_dataset.feature_name
iris_dataframe=pd.DataFrame(x_train,columns=iris_dataset.feature_names)
#create a scotter matrix  from the dataframe, color by y_train
#                           marker='o',hist_kwds=['bins':20],s=60
#                           alpha=.8,cmap=mglearn.cm3)

iris_dataframe

#building your first model: k-Nearest neighbors
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

knn.fit(x_train,y_train)#

KNeighborsClassifier(n_neighbors=1)

In [16]:
#making predictions
x_new=np.array([[5,2.9,1,0.2]])
print("x_new.shape=",x_new.shape)

from pandas.core.arrays.interval import intervals_to_interval_bounds
prediction=knn.predict(x_new)
print("pridiction=",prediction)
print("pridiction target name=",iris_dataset['target_names'][prediction])


x_new.shape= (1, 4)
pridiction= [0]
pridiction target name= ['setosa']


In [17]:
#Evaluating the model
y_pred=knn.predict(x_test)
print("Test set predictions:\n",y_pred)

y_test

y_pred==y_test

np.sum(y_pred==y_test)#true

np.sum(y_pred==y_test)/len(y_pred)

print("Test set score={:.2f}".format(np.mean(y_pred==y_test)))

print("Test set score={:.2f}".format(knn.score(x_test,y_test)))

Test set predictions:
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
Test set score=0.97
Test set score=0.97
